package utils;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.reporter.ExtentSparkReporter;
import com.aventstack.extentreports.reporter.configuration.Theme;
import net.masterthought.cucumber.Configuration;
import net.masterthought.cucumber.ReportBuilder;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
public class ReportGenerator {
    /*public static void generateReport() {
        // 1. Create a unique timestamp for the folder
        String timestamp = new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date());
        String reportDirectory = "target/cucumber-reports/Cucumber_Execution_" + timestamp;

        File reportOutputDirectory = new File(reportDirectory);
        List<String> jsonFiles = new ArrayList<>();
        // Points to the JSON generated by the Runner
        jsonFiles.add("target/cucumber-reports/cucumber.json");

        String buildNumber = "1";
        String projectName = "BDD Automation Project";

        Configuration configuration = new Configuration(reportOutputDirectory, projectName);
        configuration.setBuildNumber(buildNumber);

        // Additional metadata for the table format view
        configuration.addClassifications("Platform", "Windows 11");
        configuration.addClassifications("Browser", "Chrome");
        configuration.addClassifications("Branch", "release/v1.0");

        ReportBuilder reportBuilder = new ReportBuilder(jsonFiles, configuration);
        reportBuilder.generateReports();

        System.out.println("HTML Report generated at: " + reportDirectory + "/cucumber-html-reports/overview-features.html");
    }*/

    /* //Working for Below cucumber Html Report
     *//*#Report:
    https://gemini.google.com/app/288612452683483c?hl=en-IN
    https://gemini.google.com/app/288612452683483c?hl=en-IN
    *//*
    public static void generateHTMLReport() {
        try {
            // 1. Create a unique timestamp string
            String timestamp = new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date());

            // 2. Define the target directory path containing the execution timestamp
            String reportDirectory = System.getProperty("user.dir") + "/test-output/CucumberReports/Run_" + timestamp;
            File reportOutputDirectory = new File(reportDirectory);

            // 3. Point to the raw cucumber JSON file generated by the runner
            List<String> jsonFiles = new ArrayList<>();
            jsonFiles.add(System.getProperty("user.dir") + "/target/cucumber-reports/cucumber.json");

            // 4. Report configurations and metadata table values
            String buildNumber = "1.0";
            String projectName = "BDD Automation Test Suite";
            Configuration configuration = new Configuration(reportOutputDirectory, projectName);
            configuration.setBuildNumber(buildNumber);

            // Custom Table Environment Configurations
            configuration.addClassifications("Operating System", System.getProperty("os.name"));
            configuration.addClassifications("Execution Environment", "QA/Staging");
            configuration.addClassifications("Browser", "Chrome");

            // 5. Generate and compile the Masterthought HTML graphs and tables
            ReportBuilder reportBuilder = new ReportBuilder(jsonFiles, configuration);
            reportBuilder.generateReports();

            System.out.println("====== CUSTOM CUCUMBER REPORT GENERATED SUCCESSFULLY ======");
            System.out.println("Report Path: " + reportDirectory + "/cucumber-html-reports/overview-features.html");
            System.out.println("==========================================================");

        } catch (Exception e) {
            System.err.println("Failed to generate HTML Report: " + e.getMessage());
            e.printStackTrace();
        }
    }*/



    // Helper method to get the uniform timestamp format
    private static String getTimestamp() {
        return new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date());
    }

    /**
     * 1. Masterthought Cucumber HTML Report (Your Existing Implementation)
     */
    public static void generateHTMLReport() {
        try {
            String timestamp = getTimestamp();
            String reportDirectory = System.getProperty("user.dir") + "/test-output/CucumberReports/RunRaviCucumber_" + timestamp;
            File reportOutputDirectory = new File(reportDirectory);

            List<String> jsonFiles = new ArrayList<>();
            jsonFiles.add(System.getProperty("user.dir") + "/target/cucumber-reports/cucumber.json");

            String buildNumber = "1.0";
            String projectName = "BDD Automation Test Suite";
            Configuration configuration = new Configuration(reportOutputDirectory, projectName);
            configuration.setBuildNumber(buildNumber);

            configuration.addClassifications("Operating System", System.getProperty("os.name"));
            configuration.addClassifications("Execution Environment", "QA/Staging");
            configuration.addClassifications("Browser", "Chrome");

            ReportBuilder reportBuilder = new ReportBuilder(jsonFiles, configuration);
            reportBuilder.generateReports();

            System.out.println("====== CUSTOM CUCUMBER REPORT GENERATED SUCCESSFULLY ======");
            System.out.println("Report Path: " + reportDirectory + "/cucumber-html-reports/overview-features.html");
            System.out.println("==========================================================");
        } catch (Exception e) {
            System.err.println("Failed to generate HTML Report: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * 2. Extent Report Generator with Timestamped File Path
     * Requires dependency: com.aventstack:extentreports
     */
    /*public static void generateExtentReport() {
        try {
            String timestamp = getTimestamp();
            // Path setup matching your structure
            String reportDirectory = System.getProperty("user.dir") + "/test-output/ExtentReports/Run_" + timestamp;
            String reportPath = reportDirectory + "/ExtentReport.html";

            // Ensure folder structure is created
            File folder = new File(reportDirectory);
            if (!folder.exists()) {
                folder.mkdirs();
            }

            // Initialize Spark Reporter
            ExtentSparkReporter sparkReporter = new ExtentSparkReporter(reportPath);
            sparkReporter.config().setReportName("BDD Automation Test Execution Report");
            sparkReporter.config().setDocumentTitle("Extent Test Report");
            sparkReporter.config().setTheme(Theme.STANDARD);

            // Initialize Extent Reports engine and attach configuration
            ExtentReports extent = new ExtentReports();
            extent.attachReporter(sparkReporter);

            // Adding Custom Table Metadata matching your configuration style
            extent.setSystemInfo("Operating System", System.getProperty("os.name"));
            extent.setSystemInfo("Execution Environment", "QA/Staging");
            extent.setSystemInfo("Browser", "Chrome");
            extent.setSystemInfo("Build Number", "1.0");

            // Flush writes everything to the HTML file
            extent.flush();

            System.out.println("====== EXTENT REPORT GENERATED SUCCESSFULLY ======");
            System.out.println("Report Path: " + reportPath);
            System.out.println("==================================================");
        } catch (Exception e) {
            System.err.println("Failed to generate Extent Report: " + e.getMessage());
            e.printStackTrace();
        }
    }*/

    /**
     * 2. Programmatic Extent Report Generator (Natively from Code)
     * Generates an Extent Report using a unique timestamped file path
     * and sets up the dashboard configuration natively.
     */
    public static void generateExtentReport() {
        try {
            // 1. Create a unique timestamped directory structure
            String timestamp = getTimestamp();
            String reportDirectory = System.getProperty("user.dir") + "/test-output/ExtentReports/RunRaviExtent_" + timestamp;
            String reportPath = reportDirectory + "/ExtentReport.html";

            // 2. Ensure folder structure is completely created on disk
            File folder = new File(reportDirectory);
            if (!folder.exists()) {
                folder.mkdirs();
            }

            // 3. Initialize the Spark Reporter and design UI configuration settings
            ExtentSparkReporter sparkReporter = new ExtentSparkReporter(reportPath);
            sparkReporter.config().setReportName("BDD Automation Test Execution Dashboard");
            sparkReporter.config().setDocumentTitle("Extent Automation Test Report");
            sparkReporter.config().setTheme(Theme.STANDARD); // Use Theme.DARK if you prefer dark mode

            // 4. Initialize the core Extent Reports engine and attach our reporter configuration
            ExtentReports extent = new ExtentReports();
            extent.attachReporter(sparkReporter);

            // 5. Add Custom System Classifications matching your HTML report layout
            extent.setSystemInfo("Operating System", System.getProperty("os.name"));
            extent.setSystemInfo("Execution Environment", "QA/Staging");
            //   extent.setSystemInfo("Browser", getActiveBrowser()); // Using the dynamic browser property helper
            extent.setSystemInfo("Build Number", "1.0");
            extent.setSystemInfo("Project Name", "BDD Automation Test Suite");

            // 6. Finalize, compile, and flush all cached structural data to the HTML file
            extent.flush();

            System.out.println("====== CUSTOM EXTENT REPORT GENERATED SUCCESSFULLY ======");
            System.out.println("Report Path: " + reportPath);
            System.out.println("=========================================================");
        } catch (Exception e) {
            System.err.println("Failed to generate Extent Report: " + e.getMessage());
            e.printStackTrace();
        }
    }




    /**
     * 3. Allure Report Generator with Timestamped Output
     * Note: This programmatically invokes the 'allure commandline' binary installed on the system
     * to compile the raw json/xml results into a standalone HTML folder.
     */
    public static void generateAllureReport() {
        try {
            String timestamp = getTimestamp();
            String sourceResultsDir = System.getProperty("user.dir") + "/target/allure-results_Ravi";
            String outputReportDir = System.getProperty("user.dir") + "/test-output/AllureReports/Run_" + timestamp;

            // Runtime command execution to compile allure results into a timestamped directory
            ProcessBuilder processBuilder = new ProcessBuilder();

            // Check OS to execute proper command line routing
            if (System.getProperty("os.name").toLowerCase().contains("win")) {
                processBuilder.command("cmd.exe", "/c", "allure generate " + sourceResultsDir + " -o " + outputReportDir + " --clean");
            } else {
                processBuilder.command("bash", "-c", "allure generate " + sourceResultsDir + " -o " + outputReportDir + " --clean");
            }

            Process process = processBuilder.start();
            int exitCode = process.waitFor();

            if (exitCode == 0) {
                System.out.println("====== ALLURE REPORT GENERATED SUCCESSFULLY ======");
                System.out.println("Report Folder Path: " + outputReportDir);
                System.out.println("Open via Commandline: allure open " + outputReportDir);
                System.out.println("==================================================");
            } else {
                System.err.println("Allure command execution failed. Ensure Allure CLI is installed and added to System PATH environment variables.");
            }
        } catch (IOException | InterruptedException e) {
            System.err.println("Failed to generate Allure Report: " + e.getMessage());
            Thread.currentThread().interrupt();
        }
    }
}
